# Generated by Django 5.2.17 on 2026-09-17 12:16

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identifiant URL')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('biography', models.TextField(blank=True, verbose_name='Présentation')),
            ],
            options={
                'verbose_name': 'contributeur ou contributrice',
                'verbose_name_plural': 'contributeurs et contributrices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('rich_text', 1), ('image', 5), ('gallery', 7), ('quote', 10), ('call_to_action', 17), ('document', 19), ('columns', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link'], 'label': 'Texte enrichi'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Décrivez l’information portée par l’image. Laissez vide si elle est décorative.', 'label': 'Texte alternatif', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('alternative_text', 3), ('caption', 4)]], {'icon': 'image', 'label': 'Image'}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('alternative_text', 3), ('caption', 4)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'image', 'label': 'Galerie'}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Auteur ou source', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 9)]], {'icon': 'openquote', 'label': 'Citation'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 12: ('wagtail.blocks.TextBlock', (), {'label': 'Texte', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé'}), 14: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page interne', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'Lien externe', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('label', 13), ('page', 14), ('url', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12), ('link', 16)]], {'icon': 'pick', 'label': 'Appel à l’action'}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document'}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 13)]], {'icon': 'doc-full', 'label': 'Document à télécharger'}), 20: ('wagtail.blocks.RichTextBlock', (), {'label': 'Colonne gauche'}), 21: ('wagtail.blocks.RichTextBlock', (), {'label': 'Colonne droite'}), 22: ('wagtail.blocks.StructBlock', [[('left', 20), ('right', 21)]], {'icon': 'grip', 'label': 'Deux colonnes'})}, verbose_name='Contenu')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Réseau')),
                ('url', models.URLField(verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'lien social',
                'verbose_name_plural': 'liens sociaux',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('address', models.TextField(blank=True, verbose_name='Adresse postale')),
                ('accessibility', models.TextField(blank=True, verbose_name='Informations d’accessibilité')),
                ('map_url', models.URLField(blank=True, verbose_name='Lien vers le plan')),
            ],
            options={
                'verbose_name': 'lieu',
                'verbose_name_plural': 'lieux',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('success_message', models.CharField(default='Merci, votre message a bien été envoyé.', max_length=250, verbose_name='Message de confirmation')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(default='Alsace Bande Dessinée', max_length=200, verbose_name='Nom de l’association')),
                ('postal_address', models.TextField(blank=True, verbose_name='Adresse postale')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse e-mail publique')),
                ('legal_identifier', models.CharField(blank=True, max_length=100, verbose_name='Numéro RNA ou SIRET')),
                ('publication_director', models.CharField(blank=True, max_length=150, verbose_name='Direction de la publication')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de publication')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('image_alt', models.CharField(blank=True, max_length=250, verbose_name='Texte alternatif de l’image')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('rich_text', 1), ('image', 5), ('gallery', 7), ('quote', 10), ('call_to_action', 17), ('document', 19), ('columns', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link'], 'label': 'Texte enrichi'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Décrivez l’information portée par l’image. Laissez vide si elle est décorative.', 'label': 'Texte alternatif', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('alternative_text', 3), ('caption', 4)]], {'icon': 'image', 'label': 'Image'}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('alternative_text', 3), ('caption', 4)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'image', 'label': 'Galerie'}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Auteur ou source', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 9)]], {'icon': 'openquote', 'label': 'Citation'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 12: ('wagtail.blocks.TextBlock', (), {'label': 'Texte', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé'}), 14: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page interne', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'Lien externe', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('label', 13), ('page', 14), ('url', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12), ('link', 16)]], {'icon': 'pick', 'label': 'Appel à l’action'}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document'}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 13)]], {'icon': 'doc-full', 'label': 'Document à télécharger'}), 20: ('wagtail.blocks.RichTextBlock', (), {'label': 'Colonne gauche'}), 21: ('wagtail.blocks.RichTextBlock', (), {'label': 'Colonne droite'}), 22: ('wagtail.blocks.StructBlock', [[('left', 20), ('right', 21)]], {'icon': 'grip', 'label': 'Deux colonnes'})}, verbose_name='Contenu')),
                ('gallery', wagtail.fields.StreamField([('image', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Décrivez l’information portée par l’image. Laissez vide si elle est décorative.', 'label': 'Texte alternatif', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('alternative_text', 1), ('caption', 2)]], {})}, verbose_name='Galerie')),
                ('writer', models.CharField(blank=True, max_length=150, verbose_name='Scénariste')),
                ('artist', models.CharField(blank=True, max_length=150, verbose_name='Dessinateur ou dessinatrice')),
                ('colorist', models.CharField(blank=True, max_length=150, verbose_name='Coloriste')),
                ('publisher', models.CharField(blank=True, max_length=150, verbose_name='Maison d’édition')),
                ('featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
                ('related_articles', modelcluster.fields.ParentalManyToManyField(blank=True, to='content.blogpage', verbose_name='Chroniques associées')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='content.category', verbose_name='Catégorie')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.contributor', verbose_name='Auteur ou autrice de la chronique')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FestivalArchiveIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FestivalEditionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('dates', models.CharField(blank=True, max_length=200, verbose_name='Dates')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('retrospective', wagtail.fields.StreamField([('heading', 0), ('rich_text', 1), ('image', 5), ('gallery', 7), ('quote', 10), ('call_to_action', 17), ('document', 19), ('columns', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link'], 'label': 'Texte enrichi'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Décrivez l’information portée par l’image. Laissez vide si elle est décorative.', 'label': 'Texte alternatif', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('alternative_text', 3), ('caption', 4)]], {'icon': 'image', 'label': 'Image'}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('alternative_text', 3), ('caption', 4)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'image', 'label': 'Galerie'}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Auteur ou source', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 9)]], {'icon': 'openquote', 'label': 'Citation'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 12: ('wagtail.blocks.TextBlock', (), {'label': 'Texte', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé'}), 14: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page interne', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'Lien externe', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('label', 13), ('page', 14), ('url', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12), ('link', 16)]], {'icon': 'pick', 'label': 'Appel à l’action'}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document'}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 13)]], {'icon': 'doc-full', 'label': 'Document à télécharger'}), 20: ('wagtail.blocks.RichTextBlock', (), {'label': 'Colonne gauche'}), 21: ('wagtail.blocks.RichTextBlock', (), {'label': 'Colonne droite'}), 22: ('wagtail.blocks.StructBlock', [[('left', 20), ('right', 21)]], {'icon': 'grip', 'label': 'Deux colonnes'})}, verbose_name='Rétrospective')),
                ('programme', wagtail.fields.StreamField([('item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Horaire', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Détails', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('time', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Programme')),
                ('gallery', wagtail.fields.StreamField([('image', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Décrivez l’information portée par l’image. Laissez vide si elle est décorative.', 'label': 'Texte alternatif', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('alternative_text', 1), ('caption', 2)]], {})}, verbose_name='Galerie')),
                ('documents', wagtail.fields.StreamField([('document', 2)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé'}), 2: ('wagtail.blocks.StructBlock', [[('document', 0), ('label', 1)]], {'icon': 'doc-full', 'label': 'Document à télécharger'})}, verbose_name='Documents')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Affiche')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AuthorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('portrait_alt', models.CharField(blank=True, max_length=250, verbose_name='Texte alternatif du portrait')),
                ('biography', wagtail.fields.RichTextField(blank=True, verbose_name='Biographie')),
                ('discipline', models.CharField(blank=True, max_length=150, verbose_name='Discipline ou rôle')),
                ('country', models.CharField(blank=True, max_length=150, verbose_name='Pays ou région')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('social_url', models.URLField(blank=True, verbose_name='Réseau social')),
                ('bibliography', wagtail.fields.RichTextField(blank=True, verbose_name='Bibliographie ou œuvres choisies')),
                ('featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Portrait')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
                ('editions', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='guests', to='content.festivaleditionpage', verbose_name='Éditions')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FestivalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(default='Strasbulles', max_length=200, verbose_name='Nom du festival')),
                ('dates', models.CharField(blank=True, max_length=200, verbose_name='Dates')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('notice', models.CharField(blank=True, default='Dates et lieu à confirmer avant publication.', max_length=250, verbose_name='Mention de vérification')),
                ('newsletter_enabled', models.BooleanField(default=False, verbose_name='Afficher l’inscription à l’infolettre')),
                ('newsletter_url', models.URLField(blank=True, verbose_name='Lien d’inscription')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(default='Festival européen de la BD', max_length=100, verbose_name='Surtitre')),
                ('hero_title', models.CharField(default='Strasbulles', max_length=200, verbose_name='Titre de campagne')),
                ('hero_text', models.TextField(blank=True, verbose_name='Introduction')),
                ('primary_cta', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page interne', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Lien externe', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})}, verbose_name='Action principale')),
                ('association_intro', wagtail.fields.RichTextField(blank=True, verbose_name='Présentation de l’association')),
                ('membership_title', models.CharField(default='Faire vivre la bande dessinée en Alsace', max_length=150, verbose_name='Titre de l’appel à adhésion')),
                ('membership_text', models.TextField(blank=True, verbose_name='Texte de l’appel à adhésion')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Affiche ou image principale')),
                ('membership_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page Adhérer / Soutenir')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Libellé')),
                ('external_url', models.URLField(blank=True, verbose_name='Lien externe')),
                ('location', models.CharField(choices=[('header', 'En-tête'), ('footer', 'Pied de page')], default='footer', max_length=10, verbose_name='Emplacement')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'lien de navigation',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Afficher sur l’accueil')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'partenaire',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction courte')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('rich_text', 1), ('image', 5), ('gallery', 7), ('quote', 10), ('call_to_action', 17), ('document', 19), ('columns', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link'], 'label': 'Texte enrichi'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Décrivez l’information portée par l’image. Laissez vide si elle est décorative.', 'label': 'Texte alternatif', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('alternative_text', 3), ('caption', 4)]], {'icon': 'image', 'label': 'Image'}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('alternative_text', 3), ('caption', 4)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'image', 'label': 'Galerie'}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Auteur ou source', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 9)]], {'icon': 'openquote', 'label': 'Citation'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 12: ('wagtail.blocks.TextBlock', (), {'label': 'Texte', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé'}), 14: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page interne', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'Lien externe', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('label', 13), ('page', 14), ('url', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12), ('link', 16)]], {'icon': 'pick', 'label': 'Appel à l’action'}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document'}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 13)]], {'icon': 'doc-full', 'label': 'Document à télécharger'}), 20: ('wagtail.blocks.RichTextBlock', (), {'label': 'Colonne gauche'}), 21: ('wagtail.blocks.RichTextBlock', (), {'label': 'Colonne droite'}), 22: ('wagtail.blocks.StructBlock', [[('left', 20), ('right', 21)]], {'icon': 'grip', 'label': 'Deux colonnes'})}, verbose_name='Description')),
                ('start', models.DateTimeField(verbose_name='Début')),
                ('end', models.DateTimeField(verbose_name='Fin')),
                ('address_override', models.TextField(blank=True, verbose_name='Adresse spécifique')),
                ('map_url', models.URLField(blank=True, verbose_name='Lien vers le plan')),
                ('admission', models.CharField(blank=True, max_length=150, verbose_name='Tarif ou entrée libre')),
                ('booking_url', models.URLField(blank=True, verbose_name='Réservation ou billetterie')),
                ('image_alt', models.CharField(blank=True, max_length=250, verbose_name='Texte alternatif')),
                ('gallery', wagtail.fields.StreamField([('image', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Décrivez l’information portée par l’image. Laissez vide si elle est décorative.', 'label': 'Texte alternatif', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('alternative_text', 1), ('caption', 2)]], {})}, verbose_name='Galerie')),
                ('organiser', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='content.category', verbose_name='Catégorie')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Programme à télécharger')),
                ('related_authors', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='events', to='content.authorpage', verbose_name='Artistes associés')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='content.festivaleditionpage', verbose_name='Édition associée')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='content.venue', verbose_name='Lieu')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FestivalPage',
            fields=[
                ('standardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.standardpage')),
                ('dates', models.CharField(blank=True, max_length=250, verbose_name='Dates et horaires')),
                ('admission', models.CharField(blank=True, max_length=150, verbose_name='Tarif ou entrée libre')),
                ('programme', wagtail.fields.StreamField([('item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Horaire', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Détails', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('time', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Programme')),
                ('documents', wagtail.fields.StreamField([('document', 2)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé'}), 2: ('wagtail.blocks.StructBlock', [[('document', 0), ('label', 1)]], {'icon': 'doc-full', 'label': 'Document à télécharger'})}, verbose_name='Documents')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Affiche')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festival_pages', to='content.venue', verbose_name='Lieu')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.standardpage',),
        ),
    ]
